name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install
      run: npm install
    - name: Build app
      run: npm run generate
      env:
        FB_STAGING_APIKEY: ${{ secrets.FB_STAGING_APIKEY }}
        FB_STAGING_AUTHDOMAIN: ${{ secrets.FB_STAGING_AUTHDOMAIN }}
        FB_STAGING_DBURL: ${{ secrets.FB_STAGING_DBURL }}
        FB_STAGING_PROJECTID: ${{ secrets.FB_STAGING_PROJECTID }}
        FB_STAGING_STORAGE: ${{ secrets.FB_STAGING_STORAGE }}
        FB_STAGING_MESSAGING: ${{ secrets.FB_STAGING_MESSAGING }}
        FB_STAGING_APP: ${{ secrets.FB_STAGING_APP }}
        FB_STAGING_MEASUREMENT: ${{ secrets.FB_STAGING_MEASUREMENT }}
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FB_STAGING_PROJECTID }}
