name: Deploy to Staging
on:
  push:
    branches:
    - develop
jobs:
  main:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Install
      run: npm install
    - name: Build app
      run: npm run generate
      env:
        FB_PROD_APIKEY: ${{ secrets.FB_STAGING_APIKEY }}
        FB_PROD_AUTHDOMAIN: ${{ secrets.FB_STAGING_AUTHDOMAIN }}
        FB_PROD_DBURL: ${{ secrets.FB_STAGING_DBURL }}
        FB_PROD_PROJECTID: ${{ secrets.FB_STAGING_PROJECTID }}
        FB_PROD_STORAGE: ${{ secrets.FB_STAGING_STORAGE }}
        FB_PROD_MESSAGING: ${{ secrets.FB_STAGING_MESSAGING }}
        FB_PROD_APP: ${{ secrets.FB_STAGING_APP }}
        FB_PROD_MEASUREMENT: ${{ secrets.FB_STAGING_MEASUREMENT }}
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FB_STAGING_PROJECTID }}
